name: 'Terraform setup and plan'
description: 'Setup Terraform and creates plan'
inputs:
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  terraform_user_ocid: 
    description: 'Oracle Cloud user OCID'
    required: true
  terraform_tenant_ocid:
    description: 'Oracle Cloud Tenant OCID'
    required: true
  terraform_key_privatekey:
    description: 'Oracle Cloud API private key'
    required: true
  terraform_key_fingerprint:
    description: 'Oracle Cloud API key fingerprint'
    required: true
  tfcloud_api_token:
    description: 'TF Cloud API token for remote statefile'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
    default: 1.2.9
  github_token: 
    description: 'GitHub token for auth'
    required: true
  pr_id:
    description: 'Pull request ID'
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false
        cli_config_credentials_token: ${{ inputs.tfcloud_api_token }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
      env:
        TF_USER_OCID: ${{ inputs.terraform_user_ocid }}
        TF_TENANCY_OCID: ${{ inputs.terraform_tenant_ocid }}
        TF_PRIVATE_KEY: ${{ inputs.terraform_key_privatekey }}
        TF_FINGERPRINT: ${{ inputs.terraform_key_fingerprint }}
        TF_API_TOKEN: ${{ inputs.tfcloud_api_token }}
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}/tfplan

    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Plan:

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          Plan saved to GH artifacts.