name: Terraform Apply

on:
  pull_request_review:
    types: [submitted]

env:
  TERRAFORM_VERSION: "1.2.9"
  TF_IN_AUTOMATION: "True"

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    environment: test
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_directory: "terraform"
          terraform_user_ocid: ${{ secrets.TF_USER_OCID }}
          terraform_tenant_ocid: ${{ secrets.TF_TENANCY_OCID }}
          terraform_key_privatekey: ${{ secrets.TF_PRIVATE_KEY }}
          terraform_key_fingerprint: ${{ secrets.TF_FINGERPRINT }}
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          tfcloud_api_token: ${{ secrets.TF_API_TOKEN }}
          terraform_compartment_ocid: ${{ secrets.TF_COMPARTMENT_OCID }}
          github_token: ${{ secrets.GH_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
